'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BTMOB.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property accesspage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("accesspage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property adb() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("adb", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property AdbWinApi() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AdbWinApi", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property AdbWinUsbApi() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AdbWinUsbApi", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property androidhead() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("androidhead", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property app_disabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("app_disabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property app_enabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("app_enabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property app_locked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("app_locked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property app_nolock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("app_nolock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property app_notrak() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("app_notrak", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property app_traked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("app_traked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property apps() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("apps", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property appsedit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("appsedit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property audiosound() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audiosound", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property back2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property backshdw__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backshdw (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property battery_full() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battery_full", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property battery_low() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battery_low", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property battery_mid() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battery_mid", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property battery_mid_mins() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battery_mid_mins", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property battery_mid_plus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battery_mid_plus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property battery_oncharge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battery_oncharge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property block() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("block", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property block_con() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("block_con", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html lang=en&gt;
        '''&lt;head&gt;
        '''&lt;meta charset=UTF-8 /&gt;
        '''&lt;meta name=viewport content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        '''&lt;title&gt;&lt;/title&gt;
        '''&lt;style&gt;body{margin:0;padding:0;background-color:rgba(0,0,0,0);color:white;display:flex;justify-content:center;align-items:center;height:100vh;font-family:sans-serif;text-align:center;padding:1rem;box-sizing:border-box}.message{max-width:90vw;word-wrap:break-word}&lt;/style&gt;
        '''&lt;/head&gt;
        '''&lt;body&gt;
        '''&lt;div class=message&gt;
        '''[MSG]
        '''&lt;/div&gt;
        '''&lt;/body&gt;
        '''&lt;/html&gt;.
        '''</summary>
        Friend ReadOnly Property Block_style_black() As String
            Get
                Return ResourceManager.GetString("Block_style_black", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html lang=en&gt;
        '''&lt;head&gt;
        '''&lt;meta charset=UTF-8 /&gt;
        '''&lt;meta name=viewport content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        '''&lt;title&gt;Battery Dead&lt;/title&gt;
        '''&lt;style&gt;html,body{margin:0;padding:0;background-color:rgba(0, 0, 0, 0);height:100%;width:100%;display:flex;justify-content:center;align-items:center}.battery-vertical{width:60px;height:120px;border:4px solid #4c5b66;opacity:.7;background-color:#4c5b66;position:relative;display:flex;justify-content:center;align-items:center;box-sizing:border-box} [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Block_style_btry() As String
            Get
                Return ResourceManager.GetString("Block_style_btry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html lang=[LNG]&gt;
        '''&lt;head&gt;
        '''&lt;meta charset=UTF-8 /&gt;
        '''&lt;meta name=viewport content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        '''&lt;title&gt;Device Locked&lt;/title&gt;
        '''&lt;style&gt;*{margin:0;padding:0;box-sizing:border-box}body{background-color:#00000000;color:#fff;font-family:sans-serif;height:100vh;display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center;padding:20px}.lock-icon{font-size:48px;margin-bottom:20px}.title{font-size:20px;font-weight:bold;margin-bottom:10px}.s [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Block_style_locked() As String
            Get
                Return ResourceManager.GetString("Block_style_locked", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html lang=[LNG]&gt;
        '''&lt;head&gt;
        '''&lt;meta name=viewport content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        '''&lt;title&gt;System Update&lt;/title&gt;
        '''&lt;style&gt;body{margin:0;padding:0;background:#00000000;font-family:&apos;Helvetica Neue&apos;,sans-serif;display:flex;flex-direction:column;justify-content:center;align-items:center;height:100vh;text-align:center;color:#fff}.message{font-size:1.0rem;padding:0 20px}.warning{position:absolute;bottom:30px;font-size:.9rem;color:#ff4c4c}@media(max-width:400px){.message{font-size:1rem [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Block_style_update() As String
            Get
                Return ResourceManager.GetString("Block_style_update", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property botblue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("botblue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property botface() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("botface", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property browser() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("browser", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property BTBOTS() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("BTBOTS", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;en&quot;&gt;
        '''
        '''&lt;head&gt;
        '''    &lt;meta charset=&quot;UTF-8&quot; /&gt;
        '''    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        '''    &lt;title&gt;Chat UI&lt;/title&gt;
        '''    &lt;style&gt;
        '''        body {
        '''            margin: 0;
        '''            font-family: sans-serif;
        '''            background-color: #000000;
        '''            color: #fff;
        '''            display: flex;
        '''            flex-direction: column;
        '''            height: 100vh;
        '''            cursor: pointer;
        '''            -webkit-tap-highlight-color: rgba(0, 0, [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property btchat() As String
            Get
                Return ResourceManager.GetString("btchat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btloader() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btloader", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bttl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bttl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btunkown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btunkown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property callforword() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("callforword", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property callphone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("callphone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property camera() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("camera", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cell_tower_24dp_FFFFFF_FILL1_wght100_GRAD0_opsz24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cell_tower_24dp_FFFFFF_FILL1_wght100_GRAD0_opsz24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property clear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;[LNG]&quot;&gt;
        '''
        '''&lt;head&gt;
        '''    &lt;meta charset=&quot;UTF-8&quot; /&gt;
        '''    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        '''    &lt;title&gt;Client Version Dashboard&lt;/title&gt;
        '''    &lt;style&gt;
        '''        body {
        '''            margin: 0;
        '''            padding: 0;
        '''            font-family: sans-serif;
        '''            background: #000;
        '''            color: #f0f0f0;
        '''            cursor: pointer;
        '''            -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
        '''            -webkit-tap-highlight-color: tran [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property clientupdater() As String
            Get
                Return ResourceManager.GetString("clientupdater", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property clipico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clipico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cloneapp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cloneapp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cloneicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cloneicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property connections() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("connections", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property contacts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("contacts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;en&quot;&gt;
        '''
        '''&lt;head&gt;
        '''    &lt;meta charset=&quot;UTF-8&quot; /&gt;
        '''    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot; /&gt;
        '''    &lt;title&gt;Modern Call Keyboard&lt;/title&gt;
        '''    &lt;style&gt;
        '''        * {
        '''            touch-action: manipulation;
        '''        }
        '''
        '''        body {
        '''            margin: 0;
        '''            font-family: &apos;Segoe UI&apos;, sans-serif;
        '''            background: #000000;
        '''            display: flex;
        '''            align-items: center;
        '''            justify-content: center;
        '''            heig [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property dailer() As String
            Get
                Return ResourceManager.GetString("dailer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {&quot;Activities&quot;:&quot;0&quot;,&quot;keystrokes&quot;:&quot;1&quot;,&quot;notifications&quot;:&quot;1&quot;,&quot;visitedapps&quot;:&quot;0&quot;,&quot;visitedlinks&quot;:&quot;0&quot;,&quot;livenotify&quot;:&quot;0&quot;,&quot;livescreen&quot;:&quot;0&quot;,&quot;autoj&quot;:&quot;0&quot;}.
        '''</summary>
        Friend ReadOnly Property Deafult_mob_optns() As String
            Get
                Return ResourceManager.GetString("Deafult_mob_optns", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property delapp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delapp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property disconect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disconect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property displeapp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("displeapp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property download() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property editclint() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("editclint", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property editnote() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("editnote", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property enblapp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enblapp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property encryptoff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("encryptoff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property encrypton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("encrypton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property error_img() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("error_img", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property exs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property eye_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eye_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property eye_on() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eye_on", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property filesmanage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filesmanage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gotodir() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gotodir", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property idcard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("idcard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property info_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ject() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ject", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ject_active() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ject_active", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ject_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ject_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ject_on() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ject_on", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ject1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ject1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property keyboard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("keyboard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;en&quot;&gt;
        '''&lt;head&gt;
        '''  &lt;meta charset=&quot;UTF-8&quot; /&gt;
        '''  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;/&gt;
        '''  &lt;title&gt;Login Loading&lt;/title&gt;
        '''  &lt;style&gt;
        '''    body {
        '''      margin: 0;
        '''      background-color:#000000;
        '''      display: flex;
        '''      flex-direction: column;
        '''      align-items: center;
        '''      justify-content: center;
        '''      height: 100vh;
        '''      color: white;
        '''      font-family: Arial, sans-serif;
        '''    }
        '''
        '''    img {
        '''      max-width: 200px;
        '''      margin-bottom: [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property load() As String
            Get
                Return ResourceManager.GetString("load", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property localstore() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("localstore", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property location() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("location", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lock1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lock1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lockapp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lockapp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lockscr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lockscr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logoup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logoup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''
        '''&lt;head&gt;
        '''  &lt;meta charset=&quot;utf-8&quot; /&gt;
        '''  &lt;title&gt;Live Map&lt;/title&gt;
        '''  &lt;meta name=&quot;viewport&quot; content=&quot;initial-scale=1,maximum-scale=1,user-scalable=no&quot; /&gt;
        '''
        '''  &lt;script src=&apos;https://api.mapbox.com/mapbox-gl-js/v2.15.0/mapbox-gl.js?v2&apos;&gt;&lt;/script&gt;
        '''  &lt;link href=&apos;https://api.mapbox.com/mapbox-gl-js/v2.15.0/mapbox-gl.css?v2&apos; rel=&apos;stylesheet&apos; /&gt;
        '''  &lt;script&gt;
        '''    mapboxgl.accessToken = &apos;pk.eyJ1IjoiYWxleGtvc21hcyIsImEiOiJjbTk5c2V2MDIwZXZpMmpzZXIwZWFuaXg4In0.-9uPYTPiaZw3aPrMGWMANw&apos;;
        '''    let map; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property map() As String
            Get
                Return ResourceManager.GetString("map", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property microphone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("microphone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property myico() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("myico", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mylogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mylogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property net_2g() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("net_2g", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property net_3g() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("net_3g", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property net_4g() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("net_4g", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property net_5g() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("net_5g", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property net_vpn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("net_vpn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property newfolder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("newfolder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property no() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("no", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property no_con() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("no_con", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property noject() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noject", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property notes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property notrkapp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notrkapp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property off_lock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("off_lock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ok() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ok", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ok_con() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ok_con", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property on_lock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("on_lock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property one_ok_con() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("one_ok_con", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property open() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("open", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property paste() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paste", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property profile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("profile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redirect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redirect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redirect1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redirect1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property renamef() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("renamef", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property restart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("restart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property robot_filled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("robot_filled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scr_load() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scr_load", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scr_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scr_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scr_on() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scr_on", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property screen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("screen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property screnrader() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("screnrader", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property screnrader1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("screnrader1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sendto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sendto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sms() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sms", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property speech() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("speech", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property startapp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("startapp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sync_1x_1_0s_417px_417px_removebg_preview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sync_1x-1.0s-417px-417px-removebg-preview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;en&quot;&gt;
        '''
        '''&lt;head&gt;
        '''    &lt;meta charset=&quot;UTF-8&quot; /&gt;
        '''    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        '''    &lt;title&gt;Web Terminal&lt;/title&gt;
        '''    &lt;style&gt;
        '''        body {
        '''            margin: 0;
        '''            background-color: black;
        '''            color: lime;
        '''            font-family: monospace;
        '''            font-size: 14px;
        '''            padding: 10px;
        '''        }
        '''
        '''        #terminal {
        '''            width: 100%;
        '''            min-height: 100vh;
        '''            display: f [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property terminal() As String
            Get
                Return ResourceManager.GetString("terminal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property terminalc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("terminalc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property texttispeech() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("texttispeech", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TIT__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TIT (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property toast() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toast", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;[LNG]&quot;&gt;
        '''
        '''&lt;head&gt;
        '''    &lt;meta charset=&quot;UTF-8&quot; /&gt;
        '''    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        '''    &lt;title&gt;Transparent Bottom Toolbar&lt;/title&gt;
        '''    &lt;style&gt;
        '''        body {
        '''            margin: 0;
        '''            background-color: black;
        '''            color: white;
        '''            display: flex;
        '''            flex-direction: column;
        '''            min-height: 100vh;
        '''            justify-content: flex-end;
        '''            font-family: sans-serif;
        '''        }
        '''
        '''    [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property toolbar() As String
            Get
                Return ResourceManager.GetString("toolbar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tools() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tools", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property track() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("track", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property trkapp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("trkapp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property uninstall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("uninstall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property unlokapp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("unlokapp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property upload() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("upload", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property uploading() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("uploading", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property user() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vibratmobe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vibratmobe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vidp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vidp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wallpaper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wallpaper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property warning_img() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warning_img", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wifi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wifi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property xstop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("xstop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property zipf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zipf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
